AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 10
      DBInstanceIdentifier: mydbinstance
      Engine: 'mysql'
      MasterUsername: 'admin'
      MasterUserPassword: 'adminpassword'
      DBInstanceClass: 'db.t2.micro'
      MultiAZ: false
      PubliclyAccessible: true
